### ISSUE TITLE
Can't resolve dependencies when building

### ISSUE THREAD

**Issue by ress997** [po3rin/github_link_creator#16]
Can't build because https://github.com/po3rin/text2img doesn't exist

![08-12-35-57](https://user-images.githubusercontent.com/48500247/95412015-f104ca00-0962-11eb-9369-319ee7745239.png)

**Comment by po3rin** [comment]
This is a bug, thank you for the report!
A few minutes ago, I released v0.0.4 may recolved this issue. Please try again.
https://github.com/po3rin/github_link_creator/releases/tag/v0.4.0

**Comment by ress997** [comment]
Thank you!

We were able to build it successfully!

**Comment by po3rin** [comment]
👍
