### ISSUE TITLE
[Request] Support Qiita.

### ISSUE THREAD

**Issue by skanehira** [po3rin/github_link_creator#4]
I want to use this in Qiita But now can't use.
Would you support Qiita?

**Comment by po3rin** [comment]
I appreciate your request !

<img width="570" alt="2019-02-01 10 00 33" src="https://user-images.githubusercontent.com/29445112/52095899-3f978800-2608-11e9-80b8-d711dd625f51.png">

It is difficult to support Qiita immediately at this stage. Requests when Qiita downloads images are executed against https://camo.qiitausercontent.com, so you need to upload them to Qiita once...

We are considering another countermeasure to Qiita...
I'd like to write a note for the time being.

**Comment by skanehira** [comment]
@po3rin 
Okay, I understood that is difficult.
Thank you for considering!
